spring:
  profiles:
    active: development
  data:
    mongodb:
      host: localhost
      port: 27017
      database: library
server:
  port: 8090
---
spring:
  profiles: development
logging:
  level:
    root: INFO
---
spring:
  profiles: production
logging:
  level:
    root: ERROR